In [3]:
import pandas as pd
import numpy as np

In [8]:
a = np.random.rand(10,3)

In [9]:
a

array([[0.06163897, 0.70738563, 0.82454174],
       [0.79415038, 0.20319795, 0.40409977],
       [0.601167  , 0.86211477, 0.47307251],
       [0.96852166, 0.61878971, 0.73835962],
       [0.73249067, 0.63771405, 0.80169345],
       [0.9956758 , 0.26793225, 0.53387529],
       [0.7003868 , 0.99236707, 0.27821431],
       [0.01493035, 0.30402503, 0.89010265],
       [0.94657856, 0.35173813, 0.42337277],
       [0.03076075, 0.85646048, 0.16507405]])

In [10]:
a[-1]

array([0.03076075, 0.85646048, 0.16507405])

In [208]:
orders_file="./orders/orders-01.csv" 
orders_df = pd.read_csv(orders_file, parse_dates=True, na_values=['nan'])

In [209]:
orders_df.sort_index()

Date Symbol Order  Shares
0   2011-01-10   AAPL   BUY    1500
1   2011-01-13   AAPL  SELL    1500
2   2011-01-13    IBM   BUY    4000
3   2011-01-26   GOOG   BUY    1000
4   2011-02-02    XOM  SELL    4000
5   2011-02-10    XOM   BUY    4000
6   2011-03-03   GOOG  SELL    1000
7   2011-03-03   GOOG  SELL    2200
8   2011-06-03    IBM  SELL    3300
9   2011-05-03    IBM   BUY    1500
10  2011-06-10   AAPL   BUY    1200
11  2011-08-01   GOOG   BUY      55
12  2011-08-01   GOOG  SELL      55
13  2011-12-20   AAPL  SELL    1200
14  2011-12-21   AAPL   BUY      20
15  2011-12-27   GOOG   BUY    2200
16  2011-12-28    IBM  SELL    2200

In [210]:
b = orders_df.sort_values(by='Date')

In [211]:
b.iloc[0][1]

'AAPL'

In [212]:
c = b['Date']

In [213]:
c

0     2011-01-10
1     2011-01-13
2     2011-01-13
3     2011-01-26
4     2011-02-02
5     2011-02-10
6     2011-03-03
7     2011-03-03
9     2011-05-03
8     2011-06-03
10    2011-06-10
11    2011-08-01
12    2011-08-01
13    2011-12-20
14    2011-12-21
15    2011-12-27
16    2011-12-28
Name: Date, dtype: object

In [214]:
start_date = c[0]

In [215]:
end_date = c[len(c) - 1]

In [216]:
dates=pd.date_range(start_date,end_date)

In [217]:
df1=pd.DataFrame(index=dates)

In [218]:
df1

Empty DataFrame
Columns: []
Index: [2011-01-10 00:00:00, 2011-01-11 00:00:00, 2011-01-12 00:00:00, 2011-01-13 00:00:00, 2011-01-14 00:00:00, 2011-01-15 00:00:00, 2011-01-16 00:00:00, 2011-01-17 00:00:00, 2011-01-18 00:00:00, 2011-01-19 00:00:00, 2011-01-20 00:00:00, 2011-01-21 00:00:00, 2011-01-22 00:00:00, 2011-01-23 00:00:00, 2011-01-24 00:00:00, 2011-01-25 00:00:00, 2011-01-26 00:00:00, 2011-01-27 00:00:00, 2011-01-28 00:00:00, 2011-01-29 00:00:00, 2011-01-30 00:00:00, 2011-01-31 00:00:00, 2011-02-01 00:00:00, 2011-02-02 00:00:00, 2011-02-03 00:00:00, 2011-02-04 00:00:00, 2011-02-05 00:00:00, 2011-02-06 00:00:00, 2011-02-07 00:00:00, 2011-02-08 00:00:00, 2011-02-09 00:00:00, 2011-02-10 00:00:00, 2011-02-11 00:00:00, 2011-02-12 00:00:00, 2011-02-13 00:00:00, 2011-02-14 00:00:00, 2011-02-15 00:00:00, 2011-02-16 00:00:00, 2011-02-17 00:00:00, 2011-02-18 00:00:00, 2011-02-19 00:00:00, 2011-02-20 00:00:00, 2011-02-21 00:00:00, 2011-02-22 00:00:00, 2011-02-23 00:00:00, 2011-02-24 00:00:00, 2011-02-25 00:00:00, 2011-02-26 00:00:00, 2011-02-27 00:00:00, 2011-02-28 00:00:00, 2011-03-01 00:00:00, 2011-03-02 00:00:00, 2011-03-03 00:00:00, 2011-03-04 00:00:00, 2011-03-05 00:00:00, 2011-03-06 00:00:00, 2011-03-07 00:00:00, 2011-03-08 00:00:00, 2011-03-09 00:00:00, 2011-03-10 00:00:00, 2011-03-11 00:00:00, 2011-03-12 00:00:00, 2011-03-13 00:00:00, 2011-03-14 00:00:00, 2011-03-15 00:00:00, 2011-03-16 00:00:00, 2011-03-17 00:00:00, 2011-03-18 00:00:00, 2011-03-19 00:00:00, 2011-03-20 00:00:00, 2011-03-21 00:00:00, 2011-03-22 00:00:00, 2011-03-23 00:00:00, 2011-03-24 00:00:00, 2011-03-25 00:00:00, 2011-03-26 00:00:00, 2011-03-27 00:00:00, 2011-03-28 00:00:00, 2011-03-29 00:00:00, 2011-03-30 00:00:00, 2011-03-31 00:00:00, 2011-04-01 00:00:00, 2011-04-02 00:00:00, 2011-04-03 00:00:00, 2011-04-04 00:00:00, 2011-04-05 00:00:00, 2011-04-06 00:00:00, 2011-04-07 00:00:00, 2011-04-08 00:00:00, 2011-04-09 00:00:00, 2011-04-10 00:00:00, 2011-04-11 00:00:00, 2011-04-12 00:00:00, 2011-04-13 00:00:00, 2011-04-14 00:00:00, 2011-04-15 00:00:00, 2011-04-16 00:00:00, 2011-04-17 00:00:00, 2011-04-18 00:00:00, 2011-04-19 00:00:00, ...]

[353 rows x 0 columns]

In [219]:
len(df1)

353

In [220]:
arr = np.zeros(len(df1))

In [221]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [222]:
zeros = pd.DataFrame(arr)

In [223]:
zeros

0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
348  0.0
349  0.0
350  0.0
351  0.0
352  0.0

[353 rows x 1 columns]

In [224]:
df1 = df1.join(zeros)

In [225]:
df1

0
2011-01-10 NaN
2011-01-11 NaN
2011-01-12 NaN
2011-01-13 NaN
2011-01-14 NaN
...         ..
2011-12-24 NaN
2011-12-25 NaN
2011-12-26 NaN
2011-12-27 NaN
2011-12-28 NaN

[353 rows x 1 columns]

In [58]:
from util import get_data, plot_data

In [85]:
d = pd.date_range(start_date, end_date)

In [90]:
a = get_data(['$SPX'], d, False)
for rows in a:
    print(a, )

               $SPX
2011-01-10  1269.75
2011-01-11  1274.48
2011-01-12  1285.96
2011-01-13  1283.76
2011-01-14  1293.24
...             ...
2011-12-24      NaN
2011-12-25      NaN
2011-12-26      NaN
2011-12-27  1265.43
2011-12-28  1249.64

[353 rows x 1 columns]


In [80]:
n = a.loc[start_date]
n[0]

143.41

In [66]:
start_date

'2011-01-10'

In [72]:
a[0]

KeyError: 0

In [81]:
c = {'1':2,'3':5,'6':'hello'}
c

{'1': 2, '3': 5, '6': 'hello'}

In [82]:
for keys in c:
    print(keys)

1
3
6


In [91]:
c = NaN

NameError: name 'NaN' is not defined

In [98]:
c = np.nan


In [99]:
c

nan

In [103]:
pd.isna(c)

True

In [118]:
start_date in c.values

False

In [114]:
start_date

'2011-01-10'

In [116]:
start_date = start_date[:-1] + '1'

In [117]:
start_date

'2011-01-11'

In [151]:
df1

0
2011-01-10 NaN
2011-01-11 NaN
2011-01-12 NaN
2011-01-13 NaN
2011-01-14 NaN
...         ..
2011-12-24 NaN
2011-12-25 NaN
2011-12-26 NaN
2011-12-27 NaN
2011-12-28 NaN

[353 rows x 1 columns]

In [157]:
d = ''
count = 0
for i in df1.index:
    count += 1
    date = str(i)[:10]
    if count == 11:
        d = date
temp_dates_df = pd.date_range(d, d)
adj_close = get_data(['$SPX'], temp_dates_df, False)
adj_close

$SPX
2011-01-20  1280.26

In [146]:
c.values

array(['2011-01-10', '2011-01-13', '2011-01-13', '2011-01-26',
       '2011-02-02', '2011-02-10', '2011-03-03', '2011-03-03',
       '2011-05-03', '2011-06-03', '2011-06-10', '2011-08-01',
       '2011-08-01', '2011-12-20', '2011-12-21', '2011-12-27',
       '2011-12-28'], dtype=object)

In [150]:
for i in c.values:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [158]:
df1


0
2011-01-10 NaN
2011-01-11 NaN
2011-01-12 NaN
2011-01-13 NaN
2011-01-14 NaN
...         ..
2011-12-24 NaN
2011-12-25 NaN
2011-12-26 NaN
2011-12-27 NaN
2011-12-28 NaN

[353 rows x 1 columns]

In [165]:
type(start_date)

str

In [166]:
start_date

'2011-01-10'

In [171]:
df1.loc[pd.Timestamp(start_date)][0] = 12

In [172]:
df1

0
2011-01-10  12.0
2011-01-11   NaN
2011-01-12   NaN
2011-01-13   NaN
2011-01-14   NaN
...          ...
2011-12-24   NaN
2011-12-25   NaN
2011-12-26   NaN
2011-12-27   NaN
2011-12-28   NaN

[353 rows x 1 columns]

In [175]:
for dates in df1.index:
    print(df1.loc[dates][0])

12.0
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [176]:
a = [1,1,2,3,4,5]

In [177]:
b = {'hello':1, "world":2}


In [178]:
a[3] = b
a

[1, 1, 2, {'hello': 1, 'world': 2}, 4, 5]

In [179]:
b['wow'] = 90

In [180]:
a[5] = b 

In [181]:
a

[1,
 1,
 2,
 {'hello': 1, 'world': 2, 'wow': 90},
 4,
 {'hello': 1, 'world': 2, 'wow': 90}]

In [182]:
import copy


In [183]:
b

{'hello': 1, 'world': 2, 'wow': 90}

In [184]:
c = {'1':'hello', '2': 'damn'}

In [185]:
a = [1,2,3,4,5,6,7,8]

In [186]:
a[0] = copy.deepcopy(c)

In [187]:
a

[{'1': 'hello', '2': 'damn'}, 2, 3, 4, 5, 6, 7, 8]

In [188]:
c['69'] = 'cool'

In [189]:
a[3] = copy.deepcopy(c)

In [190]:
a

[{'1': 'hello', '2': 'damn'},
 2,
 3,
 {'1': 'hello', '2': 'damn', '69': 'cool'},
 5,
 6,
 7,
 8]

In [191]:
start_date

'2011-01-10'

In [192]:
end_date

'2011-12-28'

In [236]:
dfSPY = pd.read_csv("data/SPY.csv", index_col="Date",
						parse_dates=True, usecols=['Date','Adj Close'],
						na_values=['nan'])
dfSPY

Adj Close
Date                 
2012-09-12     144.39
2012-09-11     143.91
2012-09-10     143.51
2012-09-07     144.33
2012-09-06     143.77
...               ...
2000-02-07     114.65
2000-02-04     114.82
2000-02-03     115.30
2000-02-02     113.58
2000-02-01     113.49

[3175 rows x 1 columns]

In [195]:
df1

0
2011-01-10  12.0
2011-01-11   NaN
2011-01-12   NaN
2011-01-13   NaN
2011-01-14   NaN
...          ...
2011-12-24   NaN
2011-12-25   NaN
2011-12-26   NaN
2011-12-27   NaN
2011-12-28   NaN

[353 rows x 1 columns]

In [238]:
dfSPY = dfSPY.dropna()
dfSPY

Adj Close
Date                 
2012-09-12     144.39
2012-09-11     143.91
2012-09-10     143.51
2012-09-07     144.33
2012-09-06     143.77
...               ...
2000-02-07     114.65
2000-02-04     114.82
2000-02-03     115.30
2000-02-02     113.58
2000-02-01     113.49

[3175 rows x 1 columns]

In [241]:
df3 = df1.join(dfSPY, how='inner')

In [243]:
df3
df3.drop(columns=['Adj Close'])

0
2011-12-28 NaN
2011-12-27 NaN
2011-12-23 NaN
2011-12-22 NaN
2011-12-21 NaN
...         ..
2011-01-14 NaN
2011-01-13 NaN
2011-01-12 NaN
2011-01-11 NaN
2011-01-10 NaN

[245 rows x 1 columns]

In [234]:
df3 = df3.dropna()

In [229]:
df3

Empty DataFrame
Columns: [0, Adj Close]
Index: []

In [244]:
df1

0
2011-01-10 NaN
2011-01-11 NaN
2011-01-12 NaN
2011-01-13 NaN
2011-01-14 NaN
...         ..
2011-12-24 NaN
2011-12-25 NaN
2011-12-26 NaN
2011-12-27 NaN
2011-12-28 NaN

[353 rows x 1 columns]

In [245]:
df1.iloc[::-1]

0
2011-12-28 NaN
2011-12-27 NaN
2011-12-26 NaN
2011-12-25 NaN
2011-12-24 NaN
...         ..
2011-01-14 NaN
2011-01-13 NaN
2011-01-12 NaN
2011-01-11 NaN
2011-01-10 NaN

[353 rows x 1 columns]