In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.zeros((10,30),dtype=float)

In [4]:
a.shape

(10, 30)

In [5]:
a[3][10]=70

In [6]:
a[1][19]= 23


In [7]:
a[9][29] = 100

In [8]:
a[0][0] = 56

In [13]:
a[2][4] = 44
a[3][21] = 6969
a[4][28] = 745

In [14]:
b = pd.DataFrame(a)

In [15]:
b.head()

0    1    2    3     4    5    6    7    8    9   ...   20      21   22  \
0  56.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0     0.0  0.0   
1   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0     0.0  0.0   
2   0.0  0.0  0.0  0.0  44.0  0.0  0.0  0.0  0.0  0.0  ...  0.0     0.0  0.0   
3   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  6969.0  0.0   
4   0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0     0.0  0.0   

    23   24   25   26   27     28   29  
0  0.0  0.0  0.0  0.0  0.0    0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0    0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0    0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0    0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  745.0  0.0  

[5 rows x 30 columns]

In [17]:
np.argmax(a[4])

28

In [20]:
a[0][0]

56.0

In [21]:
type(a)

numpy.ndarray

In [22]:
d = 1


In [23]:
print("value of d is ", d)

value of d is  1


In [31]:
n = -2
if n:
    print('hello', n)

hello -2


In [32]:
t = np.zeros((100, 4, 100))

In [36]:
t.shape

(100, 4, 100)

In [41]:
t[0][0][1] = 69
t[1][2][1] = 12
t[6][3][1] = 34
t[10][1][1] = 25

In [45]:
np.argmax(t, axis = 0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0

In [50]:
np.argmax(t[1][2])

1

In [51]:
np.max(t[1][2])

12.0

In [107]:
t2 = np.full((10,4,10),-5000)

In [108]:
t.shape

(100, 4, 100)

In [109]:
t2.shape

(10, 4, 10)

In [110]:
np.max(t2[0][2])

-5000

In [121]:
t2[0][2][5] = -5000

In [122]:
np.nan + 1


nan

In [123]:
np.isnan(t2[0][0][0])

False

In [124]:
np.argmax(t2[0][2])

0

In [125]:
t3 = t2[0][2]

In [126]:
t3.shape

(10,)

In [127]:
t3

array([-5000, -5000, -5000, -5000, -5000, -5000, -5000, -5000, -5000,
       -5000])

In [128]:
np.amax(t3)

-5000

In [131]:
np.random.randint(0, 10, size=200)

array([3, 3, 7, 9, 9, 1, 6, 4, 7, 6, 6, 2, 0, 0, 6, 0, 0, 3, 9, 1, 2, 3,
       9, 8, 4, 5, 3, 0, 9, 4, 9, 1, 1, 7, 1, 9, 3, 2, 1, 7, 7, 2, 2, 2,
       0, 8, 6, 1, 4, 9, 0, 1, 2, 4, 7, 0, 5, 7, 0, 1, 2, 3, 3, 4, 7, 7,
       9, 8, 3, 6, 3, 0, 6, 7, 9, 6, 5, 6, 2, 9, 1, 0, 2, 3, 5, 9, 7, 0,
       1, 5, 3, 0, 0, 8, 7, 7, 7, 8, 4, 5, 5, 7, 0, 7, 4, 0, 4, 5, 9, 8,
       4, 7, 6, 1, 6, 7, 3, 7, 7, 1, 6, 1, 6, 4, 7, 5, 7, 7, 0, 9, 6, 9,
       0, 0, 0, 2, 3, 2, 4, 0, 3, 7, 5, 3, 1, 0, 3, 8, 5, 0, 3, 0, 5, 0,
       8, 9, 5, 0, 3, 9, 0, 4, 7, 6, 6, 2, 1, 0, 9, 5, 8, 7, 2, 6, 2, 8,
       3, 4, 5, 3, 8, 9, 7, 4, 5, 7, 4, 9, 7, 5, 7, 0, 2, 7, 2, 6, 8, 3,
       9, 7])

In [133]:
200 // 1.7


117.0

In [141]:
T = np.full((10,4,12),-1)

In [ ]:
T = 