In [1]:
import pandas as pd
import numpy as np

In [2]:
class DTLearner:
    def __init__(leaf_size = 1, verbose = False):
        self.leaf_size = leaf_size
        self.verbose = verbose
        pass
    def train(x,y):
        pass
    def query(x):
        pass

In [3]:
df = pd.read_csv('Data/Istanbul.csv', header = None, skiprows=1)  
df = df.drop(columns=0)

In [4]:
df2 = df
df2

1         2         3         4         5         6         7  \
0    0.035754  0.038376 -0.004679  0.002193  0.003894  0.000000  0.031190   
1    0.025426  0.031813  0.007787  0.008455  0.012866  0.004162  0.018920   
2   -0.028862 -0.026353 -0.030469 -0.017833 -0.028735  0.017293 -0.035899   
3   -0.062208 -0.084716  0.003391 -0.011726 -0.000466 -0.040061  0.028283   
4    0.009860  0.009658 -0.021533 -0.019873 -0.012710 -0.004474 -0.009764   
..        ...       ...       ...       ...       ...       ...       ...   
531  0.008599  0.013400  0.006238  0.001925  0.007952  0.005717  0.018371   
532  0.009310  0.015977  0.003071 -0.001186  0.000345  0.002620  0.001686   
533  0.000191 -0.001653  0.001923  0.002872 -0.000723  0.000568  0.005628   
534 -0.013069 -0.013706 -0.020742 -0.014239 -0.011275  0.001358 -0.011942   
535 -0.007246 -0.019442  0.000000 -0.000473 -0.002997 -0.017920 -0.012252   

            8         9  
0    0.012698  0.028524  
1    0.011341  0.008773  
2   -0.017073 -0.020015  
3   -0.005561 -0.019424  
4   -0.010989 -0.007802  
..        ...       ...  
531  0.006975  0.003039  
532 -0.000581  0.001039  
533  0.000572  0.006938  
534 -0.012615 -0.000958  
535 -0.005465 -0.014297  

[536 rows x 9 columns]

In [5]:
# here's how to get the last column
df2.iloc[:,-1:]

9
0    0.028524
1    0.008773
2   -0.020015
3   -0.019424
4   -0.007802
..        ...
531  0.003039
532  0.001039
533  0.006938
534 -0.000958
535 -0.014297

[536 rows x 1 columns]

In [6]:
best_correlation = -10000
for col_data in df2.columns[:-1]:
    print('col data', col_data)
    correlation = df2[col_data].corr(df2[df2.columns[-1]])
    if abs(correlation) > best_correlation:
        best_correlation = correlation
    print(df2[col_data].corr(df2[df2.columns[-1]]))
print('best is ', best_correlation)

col data 1
0.6002952779745133
col data 2
0.7019537908167133
col data 3
0.5282432012738653
col data 4
0.6651624791060335
col data 5
0.6875434030528024
col data 6
0.5472879690040532
col data 7
0.6880735475385332
col data 8
0.7165016749061555
best is  0.7165016749061555


In [7]:
arr = df2.to_numpy()
arr.astype(np.float)

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       ...,
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [8]:
# for i in arr.T[:-1]:
#     #print(i.shape, arr[:,1].shape)
#     a = np.corrcoef(i, y=arr[:,-1])
    
#     #print(np.corrcoef(i, y=arr[:,-1]))
#     print(a[0][1])
t = arr.T
best_correlation = -10000
idx= -1
for i in range(t.shape[0] -1):
    #print(i.shape, arr[:,1].shape)
    a = np.corrcoef(t[i], y=arr[:,-1])
    
    if abs(correlation) > best_correlation:
        best_correlation = correlation
        idx = i


In [9]:
best_correlation

0.7165016749061555

In [10]:
idx

0

In [11]:
median = np.median(t[idx])
median

0.002188758

In [12]:
m2 = np.median(arr[:,idx])
m2

0.002188758

In [13]:
z = arr[arr[:,idx]<=median]

In [14]:
z.shape

(268, 9)

In [15]:
z

array([[-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       [-0.06220808, -0.0847159 ,  0.00339136, ...,  0.02828315,
        -0.00556096, -0.01942378],
       [-0.02919103, -0.04236115, -0.02282263, ..., -0.05384947,
        -0.01245126, -0.02262974],
       ...,
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [16]:
y = arr[arr[:,idx]>median]

In [17]:
y.shape

(268, 9)

In [18]:
d = pd.DataFrame(y)

In [19]:
d.head()

0         1         2         3         4         5         6  \
0  0.035754  0.038376 -0.004679  0.002193  0.003894  0.000000  0.031190   
1  0.025426  0.031813  0.007787  0.008455  0.012866  0.004162  0.018920   
2  0.009860  0.009658 -0.021533 -0.019873 -0.012710 -0.004474 -0.009764   
3  0.015445 -0.000272  0.001757 -0.017674 -0.006141  0.000000  0.003572   
4  0.022037  0.032278  0.007533  0.006791  0.006289  0.025453  0.004867   

          7         8  
0  0.012698  0.028524  
1  0.011341  0.008773  
2 -0.010989 -0.007802  
3 -0.012220 -0.004827  
4  0.008561  0.010917

In [20]:
y

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [ 0.00985991,  0.00965811, -0.02153321, ..., -0.00976388,
        -0.01098863, -0.00780221],
       ...,
       [ 0.00360638,  0.00089272, -0.0032402 , ..., -0.00326564,
        -0.00054988, -0.00143045],
       [ 0.00859906,  0.0133999 ,  0.00623799, ...,  0.01837079,
         0.00697461,  0.00303899],
       [ 0.00931031,  0.0159772 ,  0.00307089, ...,  0.00168569,
        -0.00058051,  0.00103859]])

In [21]:
y[0]

array([ 0.03575371,  0.03837619, -0.00467931,  0.00219342,  0.00389438,
        0.        ,  0.03119023,  0.01269804,  0.02852446])

In [22]:
np.min(y[:,0])

0.002192959

In [23]:
np.max(z[:,0])

0.002184557

In [24]:
a = np.empty((0,3))
a

array([], shape=(0, 3), dtype=float64)

In [25]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape

(2, 3)

In [26]:
a = np.append(a, arr2)

In [27]:
a

array([1., 2., 3., 4., 5., 6.])

In [28]:
a.shape

(6,)

In [35]:
em = np.empty((0,5))
em

array([], shape=(0, 5), dtype=float64)

In [36]:
arr2 = np.array([[1, 2, 3, 9, 49], [4, 5, 6, 69, 12]])

In [37]:
arr2

array([[ 1,  2,  3,  9, 49],
       [ 4,  5,  6, 69, 12]])

In [38]:
arr2.shape

(2, 5)

In [40]:
em = np.vstack((em, arr2))

In [34]:
em

array([[ 1.,  2.,  3.,  9., 49.],
       [ 4.,  5.,  6., 69., 12.]])

In [41]:
em.shape

(2, 5)

In [42]:
arr3 = np.array([[8, 45, 33, 93, 49]])

In [43]:
em = np.vstack((em, arr3))

In [44]:
em

array([[ 1.,  2.,  3.,  9., 49.],
       [ 4.,  5.,  6., 69., 12.],
       [ 8., 45., 33., 93., 49.]])

In [72]:
root = np.array([2,.11,1,8])

In [73]:
root


array([2.  , 0.11, 1.  , 8.  ])

In [74]:
root.shape

(4,)

In [75]:
root = np.vstack((root, [2,3,4,5],[4,5,6,7]))

In [76]:
root

array([[2.  , 0.11, 1.  , 8.  ],
       [2.  , 3.  , 4.  , 5.  ],
       [4.  , 5.  , 6.  , 7.  ]])

In [77]:
root.shape

(3, 4)

In [79]:
x = np.array([[1,2,3],[4,5,7]])
x

array([[1, 2, 3],
       [4, 5, 7]])

In [80]:
y = np.array([[2],[5]])

In [81]:
y

array([[2],
       [5]])

In [82]:
data = np.append(x,y,axis=1)

In [83]:
data

array([[1, 2, 3, 2],
       [4, 5, 7, 5]])

In [133]:
c = np.zeros((30,2))
c.shape

(30, 2)

In [134]:
b = np.zeros((30,))
b.shape

(30,)

In [135]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [136]:
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [137]:
b.shape

(30,)

In [138]:
c.shape

(30, 2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
df = pd.DataFrame(b)
df

0
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0
5   0.0
6   0.0
7   0.0
8   0.0
9   0.0
10  0.0
11  0.0
12  0.0
13  0.0
14  0.0
15  0.0
16  0.0
17  0.0
18  0.0
19  0.0
20  0.0
21  0.0
22  0.0
23  0.0
24  0.0
25  0.0
26  0.0
27  0.0
28  0.0
29  0.0

In [139]:
d = np.append(c,b,1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [132]:
df = pd.DataFrame(d)
df

0
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0
..  ...
85  0.0
86  0.0
87  0.0
88  0.0
89  0.0

[90 rows x 1 columns]

In [140]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [141]:
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [142]:
d = np.column_stack((b,c))

In [143]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [158]:
y = np.empty(0)
y

array([], dtype=float64)

In [159]:
y = np.append(y, 1)

In [160]:
y

array([1.])

In [161]:
y = np.append(y, 9)

In [162]:
y

array([1., 9.])

In [163]:
a = np.NAN
a

nan

In [164]:
a == np.NAN

False

In [165]:
a is np.NAN

True

In [166]:
a = np.array([1])
a[0]

1

In [167]:
a[0] is np.NAN

False

In [168]:
arr

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       ...,
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [169]:
arr.shape

(536, 9)

In [171]:
len(arr[:,4])

536

In [173]:
np.mean(arr[:,-1])

0.0009359355858208956

In [175]:
z = np.empty_like(arr)
z.shape

(536, 9)

In [176]:
z[:] = arr

In [177]:
z

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       ...,
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [178]:
z.shape

(536, 9)

In [180]:
np.delete(z, 3, 1).shape

(536, 8)

In [181]:
a = np.array([np.NAN, 1, np.NAN, np.NAN])

In [182]:
a

array([nan,  1., nan, nan])

In [184]:
a.shape

(4,)

In [185]:
a = np.array([[np.NAN, 1, np.NAN, np.NAN]])

In [186]:
a.shape

(1, 4)

In [187]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [191]:
np.median(a)

5.5

In [189]:
a.shape

(5,)

In [190]:
a = np.array([6,5,6,5,6,5,6,5,6,5,6,5])

In [192]:
arr

array([[ 0.03575371,  0.03837619, -0.00467931, ...,  0.03119023,
         0.01269804,  0.02852446],
       [ 0.02542587,  0.03181274,  0.00778674, ...,  0.01891958,
         0.01134065,  0.00877264],
       [-0.02886173, -0.02635297, -0.03046913, ..., -0.03589858,
        -0.0170728 , -0.02001541],
       ...,
       [ 0.00019097, -0.0016526 ,  0.00192291, ...,  0.00562792,
         0.00057157,  0.00693787],
       [-0.01306904, -0.01370599, -0.02074215, ..., -0.01194168,
        -0.01261533, -0.00095774],
       [-0.00724632, -0.01944185,  0.        , ..., -0.01225155,
        -0.00546489, -0.01429693]])

In [193]:
arr.shape

(536, 9)

In [195]:
b = arr.shape[1]
b

9

In [202]:
np.random.randint(low=0,high=9)

3

In [204]:
arr[:,8]

array([ 2.8524462e-02,  8.7726440e-03, -2.0015412e-02, -1.9423778e-02,
       -7.8022120e-03, -2.2629745e-02, -4.8271380e-03, -8.6766460e-03,
       -2.3428729e-02,  1.0916893e-02, -4.0290040e-03, -2.4107193e-02,
       -5.0922420e-03, -3.2272490e-03, -8.0773190e-03,  1.0319685e-02,
        6.3444980e-03,  2.2104103e-02,  4.0869700e-04,  2.2425390e-03,
       -1.9091385e-02,  1.2718686e-02,  1.5165589e-02,  2.0725050e-03,
        3.2338114e-02,  7.8953940e-03, -2.1390950e-03, -7.9259970e-03,
       -1.4772748e-02,  1.7764444e-02, -6.8504410e-03, -3.8322771e-02,
       -3.3422610e-03,  6.7644980e-03, -2.7294442e-02,  9.6778700e-03,
       -1.1881112e-02,  6.0993640e-03, -2.3311640e-03, -6.1501310e-03,
       -3.5364882e-02,  1.2903070e-03,  3.0311506e-02, -8.6718380e-03,
       -2.0976470e-03, -5.5583640e-03,  2.4909954e-02,  1.2815720e-02,
        5.4194750e-03,  1.8689238e-02,  1.0253879e-02,  2.6886910e-03,
        6.0125060e-03,  9.8472740e-03, -6.6543520e-03,  4.4121571e-02,
      