In [2]:
import pandas as pd
import numpy as np

In [6]:
rows = np.random.randint(10, 1001)
rows

321

In [7]:
cols = np.random.randint(2, 11)
cols

3

In [8]:
x = np.random.rand(rows, cols)
x

array([[0.76178388, 0.95713969, 0.09273254],
       [0.3766331 , 0.05487355, 0.88713014],
       [0.09597259, 0.37381488, 0.44834893],
       [0.42465199, 0.78532308, 0.76078321],
       [0.2164447 , 0.83404972, 0.91776183],
       [0.85203746, 0.18830989, 0.90824026],
       [0.21892364, 0.44679414, 0.93573194],
       [0.99739092, 0.0430811 , 0.83613349],
       [0.10447792, 0.20285659, 0.89851767],
       [0.16492009, 0.30063294, 0.92544807],
       [0.66206499, 0.176655  , 0.49115344],
       [0.01355569, 0.4784895 , 0.4404717 ],
       [0.11628755, 0.77868328, 0.55867678],
       [0.71227064, 0.85207172, 0.1872558 ],
       [0.85176512, 0.31355434, 0.20133897],
       [0.14572167, 0.39149337, 0.82160636],
       [0.68652044, 0.74011143, 0.97154697],
       [0.928007  , 0.78506931, 0.83106845],
       [0.66669429, 0.10824756, 0.3144771 ],
       [0.54366731, 0.55136793, 0.94633301],
       [0.10838386, 0.69333084, 0.13694983],
       [0.83077734, 0.82378746, 0.95328857],
       [0.

In [10]:
pd.DataFrame(x)

0         1         2
0    0.761784  0.957140  0.092733
1    0.376633  0.054874  0.887130
2    0.095973  0.373815  0.448349
3    0.424652  0.785323  0.760783
4    0.216445  0.834050  0.917762
..        ...       ...       ...
316  0.013228  0.247125  0.012842
317  0.271816  0.464918  0.475422
318  0.927405  0.081287  0.162411
319  0.095506  0.794404  0.861825
320  0.111920  0.233995  0.388323

[321 rows x 3 columns]

In [16]:
# better data for decision trees
y = x.mean(1)
y = y * y
y

array([0.36467754, 0.19320033, 0.09366383, 0.43154313, 0.43044807,
       0.42188818, 0.28496014, 0.39129425, 0.16156439, 0.21498712,
       0.19650704, 0.09662086, 0.23478793, 0.34089957, 0.20752836,
       0.20515507, 0.63902908, 0.71918584, 0.1318704 , 0.46302048,
       0.09789901, 0.75565546, 0.14095226, 0.32064671, 0.36192019,
       0.1420702 , 0.12216268, 0.30031252, 0.17652412, 0.20260547,
       0.05706025, 0.04423994, 0.04556748, 0.35937534, 0.11585459,
       0.00675537, 0.2175812 , 0.18884235, 0.39954323, 0.29015296,
       0.14892531, 0.12241773, 0.23353534, 0.05338281, 0.41547508,
       0.50203469, 0.60582414, 0.50953741, 0.01132727, 0.18908868,
       0.20748067, 0.15734559, 0.37809554, 0.11513452, 0.11212743,
       0.28037561, 0.22860844, 0.4852817 , 0.34942898, 0.13636028,
       0.47191343, 0.37971791, 0.23333303, 0.18956691, 0.15757478,
       0.06256327, 0.28538684, 0.09565814, 0.07321133, 0.55942273,
       0.08677244, 0.20600001, 0.73996635, 0.28316728, 0.32760

In [17]:
pd.DataFrame(y)

0
0    0.364678
1    0.193200
2    0.093664
3    0.431543
4    0.430448
..        ...
316  0.008293
317  0.163258
318  0.152387
319  0.340953
320  0.059901

[321 rows x 1 columns]

In [19]:
# better data for linear regression
m = 2
b = 0
y2 = m * x.mean(1) + b
y2

array([1.20777074, 0.8790912 , 0.61209093, 1.31383885, 1.31217083,
       1.2990584 , 1.06763315, 1.25107034, 0.80390146, 0.92733406,
       0.88658229, 0.62167793, 0.96909841, 1.1677321 , 0.91110562,
       0.90588093, 1.59878589, 1.69609651, 0.72627929, 1.36091217,
       0.62577636, 1.73856891, 0.75087218, 1.13251351, 1.20319605,
       0.75384401, 0.69903558, 1.09601554, 0.84029546, 0.90023435,
       0.47774575, 0.42066587, 0.42693079, 1.19895845, 0.6807484 ,
       0.16438208, 0.93291199, 0.86911991, 1.26418864, 1.07731697,
       0.77181684, 0.69976489, 0.96650988, 0.46209443, 1.28914713,
       1.41708812, 1.55669412, 1.42763778, 0.21285932, 0.86968657,
       0.91100093, 0.79333623, 1.22978947, 0.67862955, 0.66970867,
       1.05901013, 0.95626031, 1.39324327, 1.18225037, 0.73853987,
       1.37391911, 1.2324251 , 0.96609115, 0.87078564, 0.7939138 ,
       0.50025301, 1.06843221, 0.61857301, 0.54115184, 1.49589135,
       0.58914324, 0.90774447, 1.72042594, 1.06426929, 1.14473

In [20]:
pd.DataFrame(y2)

0
0    1.207771
1    0.879091
2    0.612091
3    1.313839
4    1.312171
..        ...
316  0.182130
317  0.808104
318  0.780736
319  1.167824
320  0.489492

[321 rows x 1 columns]

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
pd.DataFrame(a)


0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
b = a[:, 0]

In [6]:
b

array([1, 4, 7])

In [31]:
z = np.random.randint(1,3)
z

2